# Generated by Django 5.0.7 on 2024-07-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='id',
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
