# Generated by Django 5.0.7 on 2024-07-29 13:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_booking_id_alter_booking_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='retreat',
            name='condition',
            field=models.CharField(default='Default Condition', max_length=255),
        ),
        migrations.AddField(
            model_name='retreat',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='retreat',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='retreat',
            name='image',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='retreat',
            name='tag',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='retreat',
            name='type',
            field=models.CharField(default='General', max_length=255),
        ),
    ]
