# Generated by Django 5.0.7 on 2024-07-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_retreat_condition_retreat_date_retreat_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retreat',
            name='date',
            field=models.DateField(),
        ),
    ]
